name: "Epoxy Granite Mill"
board: "ESP32 Dev Controller V4"


# System Controls
start:
  check_limits: true
  must_home: false
  deactivate_parking: false
control:
  estop_pin: gpio.12:pd


# SD Card
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 8000000


# OLED Display
i2c0:
  sda_pin: gpio.13
  scl_pin: gpio.14
oled:
  type: "SH1106"
  i2c_num: 0
  i2c_address: 60
  width: 128
  height: 64
  radio_delay_ms: 1000


# Spindle VFD (H100)
#uart1:
#  rxd_pin: gpio.25
#  rts_pin: gpio.26
#  txd_pin: gpio.27
#  baud: 9600
#  mode: 8N1
#H100:
#  uart_num: 1
#  modbus_id: 1
#  tool_num: 0
#  speed_map: 0=0% 750=25% 1500=50% 3000=100%


# I2SO Outputs (step/dir)
i2so:
  bck_pin: gpio.4
  ws_pin: gpio.0
  data_pin: gpio.2
stepping:
  engine: I2S_STATIC
  idle_ms: 10000
  dir_delay_us: 1
  pulse_us: 5
  disable_delay_us: 0


axes:

  x:
    # 4 mm pitch
    steps_per_mm: 500
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 1000
    motor0:
      limit_neg_pin: gpio.1:low
      limit_pos_pin: gpio.22:low
      hard_limits: false
      stepstick:
        step_pin: i2so.4
        direction_pin: i2so.5:low
    mpg:
      a_pin: gpio.36
      b_pin: gpio.39
      reverse: true
      pulses_per_rev: 500
      max_rpm: 240.0
      max_rate_factor: 0.5


  y:
    # 5 mm pitch
    steps_per_mm: 400
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 1000
    motor0:
      limit_neg_pin: gpio.3:low
      limit_pos_pin: gpio.21:low
      hard_limits: false
      stepstick:
        step_pin: i2so.2
        direction_pin: i2so.3:low
    mpg:
      a_pin: gpio.34
      b_pin: gpio.35
      reverse: true
      pulses_per_rev: 500
      max_rpm: 240.0
      max_rate_factor: 0.5


  z:

    steps_per_mm: 314.96
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 1000
    max_travel_mm: 1000
    motor0:
      limit_neg_pin: gpio.17:low
      limit_pos_pin: gpio.16:low
      hard_limits: false
      stepstick:
        step_pin: i2so.0
        direction_pin: i2so.1
    mpg:
      a_pin: gpio.32
      b_pin: gpio.33
      reverse: true
      pulses_per_rev: 500
      max_rpm: 240.0
      max_rate_factor: 0.5
