name: "Southbend Lathe"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 5
  disable_delay_us: 0

axes:

  x:
    steps_per_mm: 1470.12
    max_rate_mm_per_min: 750
    acceleration_mm_per_sec2: 75
    max_travel_mm: 1000
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
    
    motor0:
      stepstick:
        step_pin: gpio.13
        direction_pin: gpio.27:low
    motor1:
      null_motor:
