board: "ESP32v4"
name: "Southbend Lathe"
meta: "machine:LATHE"

start:
  check_limits: false
  must_home: false
  deactivate_parking: false

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 6
  disable_delay_us: 0

synchro:
  index_pin: gpio.32

axes:

  x:
    steps_per_mm: 1470.12
    max_rate_mm_per_min: 750
    acceleration_mm_per_sec2: 75
    max_travel_mm: 1000
    motor0:
      stepstick:
        step_pin: gpio.13
        direction_pin: gpio.27:low
    homing:
      cycle: 2
      mpos_mm: 10
      positive_direction: false
